# Biosensing Data Analysis by Machine Learning

# Import Libraries for Analysis

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import sklearn

In [2]:
df = pd.read_csv("Biosensing_Dataset.csv")

In [4]:
df.head()

,Sample_ID,Batch_ID,Biological_Group,Peak_Current_uA,Peak_Potential_mV,Charge_Transfer_Resistance_Ohm,Impedance_Ohm,Peak_Charge_uC,Sensitivity_uA_per_ng_mL,Signal_to_Noise_Ratio,...,Metabolite_14,Metabolite_15,Metabolite_16,Metabolite_17,Metabolite_18,Metabolite_19,Metabolite_20,Target_Analyte_Concentration_ng_mL,Detection_Label,Analyte_Class
0,S00001,19,3,3.080973,282.168307,454.726858,493.791554,1.952251,2.059935,0.758591,...,1.066286,1.760552,2.464147,0.713059,0.061526,2.358170,1.624034,2.580320,1,2
1,S00002,20,2,1.707168,273.729245,499.006676,516.457266,1.262311,0.943410,2.047740,...,1.386526,1.409253,1.304545,0.150607,1.197033,0.408493,1.175733,2.128033,1,2
2,S00003,19,1,1.813048,297.271022,439.124155,437.019953,2.667857,1.278415,2.642561,...,2.215326,1.365319,1.283307,0.687568,0.666905,2.123052,1.986004,6.015071,1,3
3,S00004,9,3,1.244136,288.331230,423.259121,434.957070,2.584344,1.984862,1.026319,...,2.699094,1.481016,0.809282,1.499262,1.916961,1.047749,1.684955,5.832540,1,3
4,S00005,19,3,1.530964,245.279230,565.924739,527.080952,1.587169,0.752915,0.707191,...,0.020578,1.108002,1.376402,2.077493,0.499590,0.498678,1.009440,0.745621,0,1

In [5]:
df.shape

(20000, 81)

In [6]:
df.columns

Index(['Sample_ID', 'Batch_ID', 'Biological_Group', 'Peak_Current_uA',
       'Peak_Potential_mV', 'Charge_Transfer_Resistance_Ohm', 'Impedance_Ohm',
       'Peak_Charge_uC', 'Sensitivity_uA_per_ng_mL', 'Signal_to_Noise_Ratio',
       'Baseline_Current_uA', 'Response_Time_s', 'Double_Layer_Capacitance_uF',
       'Faradaic_Current_uA', 'Open_Circuit_Potential_mV', 'Peak_Width_mV',
       'Electrode_Stability_pct', 'Calibration_Slope', 'Protein_01',
       'Protein_02', 'Protein_03', 'Protein_04', 'Protein_05', 'Protein_06',
       'Protein_07', 'Protein_08', 'Protein_09', 'Protein_10', 'Protein_11',
       'Protein_12', 'Protein_13', 'Protein_14', 'Protein_15', 'Protein_16',
       'Protein_17', 'Protein_18', 'Protein_19', 'Protein_20', 'Gene_01',
       'Gene_02', 'Gene_03', 'Gene_04', 'Gene_05', 'Gene_06', 'Gene_07',
       'Gene_08', 'Gene_09', 'Gene_10', 'Gene_11', 'Gene_12', 'Gene_13',
       'Gene_14', 'Gene_15', 'Gene_16', 'Gene_17', 'Gene_18', 'Gene_19',
       'Gene_20', 'Metabolite_01', 'Metabolite_02', 'Metabolite_03',
       'Metabolite_04', 'Metabolite_05', 'Metabolite_06', 'Metabolite_07',
       'Metabolite_08', 'Metabolite_09', 'Metabolite_10', 'Metabolite_11',
       'Metabolite_12', 'Metabolite_13', 'Metabolite_14', 'Metabolite_15',
       'Metabolite_16', 'Metabolite_17', 'Metabolite_18', 'Metabolite_19',
       'Metabolite_20', 'Target_Analyte_Concentration_ng_mL',
       'Detection_Label', 'Analyte_Class'],
      dtype='str')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 81 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Sample_ID                           20000 non-null  str
 1   Batch_ID                            20000 non-null  int64
 2   Biological_Group                    20000 non-null  int64
 3   Peak_Current_uA                     19883 non-null  float64
 4   Peak_Potential_mV                   19876 non-null  float64
 5   Charge_Transfer_Resistance_Ohm      19864 non-null  float64
 6   Impedance_Ohm                       19871 non-null  float64
 7   Peak_Charge_uC                      19871 non-null  float64
 8   Sensitivity_uA_per_ng_mL            19862 non-null  float64
 9   Signal_to_Noise_Ratio               19886 non-null  float64
 10  Baseline_Current_uA                 19885 non-null  float64
 11  Response_Time_s                     19890 non-null  float64
 12  Double_Layer_Capacitance_uF         19896 non-null  float64
 13  Faradaic_Current_uA                 19864 non-null  float64
 14  Open_Circuit_Potential_mV           19882 non-null  float64
 15  Peak_Width_mV                       19870 non-null  float64
 16  Electrode_Stability_pct             19876 non-null  float64
 17  Calibration_Slope                   19871 non-null  float64
 18  Protein_01                          19907 non-null  float64
 19  Protein_02                          19880 non-null  float64
 20  Protein_03                          19877 non-null  float64
 21  Protein_04                          19898 non-null  float64
 22  Protein_05                          19875 non-null  float64
 23  Protein_06                          19871 non-null  float64
 24  Protein_07                          19889 non-null  float64
 25  Protein_08                          19893 non-null  float64
 26  Protein_09                          19884 non-null  float64
 27  Protein_10                          19883 non-null  float64
 28  Protein_11                          19904 non-null  float64
 29  Protein_12                          19877 non-null  float64
 30  Protein_13                          19894 non-null  float64
 31  Protein_14                          19856 non-null  float64
 32  Protein_15                          19868 non-null  float64
 33  Protein_16                          19895 non-null  float64
 34  Protein_17                          19880 non-null  float64
 35  Protein_18                          19880 non-null  float64
 36  Protein_19                          19893 non-null  float64
 37  Protein_20                          19889 non-null  float64
 38  Gene_01                             19886 non-null  float64
 39  Gene_02                             19880 non-null  float64
 40  Gene_03                             19884 non-null  float64
 41  Gene_04                             19880 non-null  float64
 42  Gene_05                             19866 non-null  float64
 43  Gene_06                             19876 non-null  float64
 44  Gene_07                             19870 non-null  float64
 45  Gene_08                             19883 non-null  float64
 46  Gene_09                             19873 non-null  float64
 47  Gene_10                             19887 non-null  float64
 48  Gene_11                             19877 non-null  float64
 49  Gene_12                             19894 non-null  float64
 50  Gene_13                             19864 non-null  float64
 51  Gene_14                             19875 non-null  float64
 52  Gene_15                             19873 non-null  float64
 53  Gene_16                             19882 non-null  float64
 54  Gene_17                             19876 non-null  float64
 55  Gene_18                             19884 non-null  float64
 56  Gene_19                             19860 non-null  float64
 57  Gene_20                             19897 non-null  float64
 58  Metabolite_01                       19859 non-null  float64
 59  Metabolite_02                       19872 non-null  float64
 60  Metabolite_03                       19879 non-null  float64
 61  Metabolite_04                       19887 non-null  float64
 62  Metabolite_05                       19897 non-null  float64
 63  Metabolite_06                       19866 non-null  float64
 64  Metabolite_07                       19899 non-null  float64
 65  Metabolite_08                       19871 non-null  float64
 66  Metabolite_09                       19887 non-null  float64
 67  Metabolite_10                       19890 non-null  float64
 68  Metabolite_11                       19878 non-null  float64
 69  Metabolite_12                       19880 non-null  float64
 70  Metabolite_13                       19872 non-null  float64
 71  Metabolite_14                       19846 non-null  float64
 72  Metabolite_15                       19869 non-null  float64
 73  Metabolite_16                       19865 non-null  float64
 74  Metabolite_17                       19883 non-null  float64
 75  Metabolite_18                       19894 non-null  float64
 76  Metabolite_19                       19880 non-null  float64
 77  Metabolite_20                       19870 non-null  float64
 78  Target_Analyte_Concentration_ng_mL  20000 non-null  float64
 79  Detection_Label                     20000 non-null  int64
 80  Analyte_Class                       20000 non-null  int64
dtypes: float64(76), int64(4), str(1)
memory usage: 12.4 MB

In [8]:
df.describe()

,Batch_ID,Biological_Group,Peak_Current_uA,Peak_Potential_mV,Charge_Transfer_Resistance_Ohm,Impedance_Ohm,Peak_Charge_uC,Sensitivity_uA_per_ng_mL,Signal_to_Noise_Ratio,Baseline_Current_uA,...,Metabolite_14,Metabolite_15,Metabolite_16,Metabolite_17,Metabolite_18,Metabolite_19,Metabolite_20,Target_Analyte_Concentration_ng_mL,Detection_Label,Analyte_Class
count,20000.000000,20000.00000,19883.000000,19876.000000,19864.000000,19871.000000,19871.000000,19862.000000,19886.000000,19885.000000,...,19846.000000,19869.000000,19865.000000,19883.000000,19894.000000,19880.000000,19870.000000,20000.000000,20000.000000,20000.000000
mean,10.496400,1.51115,1.155695,281.231243,450.653862,450.620156,1.540286,1.105115,1.402871,1.518547,...,1.504943,1.484855,1.504754,1.501853,1.499164,1.504359,1.491184,4.834514,0.937400,2.259950
std,5.771391,1.11747,0.720419,18.786227,43.548106,43.894507,0.850913,0.698869,0.802661,0.838726,...,0.817168,0.292709,0.700002,0.719684,0.816730,0.778990,0.327110,4.304633,0.242248,0.593122
min,1.000000,0.00000,-1.687768,222.855054,290.106823,275.398361,-1.571478,-1.573737,-1.253174,-1.373504,...,-1.641779,0.682749,-1.116511,-1.583464,-1.620630,-2.516650,0.627394,0.112691,0.000000,0.000000
25%,6.000000,1.00000,0.669017,267.856265,421.824512,421.710080,0.953421,0.625825,0.846596,0.939723,...,0.947556,1.279624,1.035351,1.012817,0.949154,0.985792,1.257473,2.027988,1.000000,2.000000
50%,11.000000,2.00000,1.141967,280.130660,452.474637,452.385399,1.522101,1.094928,1.391754,1.496041,...,1.514654,1.454405,1.503979,1.499080,1.499733,1.506604,1.454771,3.495358,1.000000,2.000000
75%,16.000000,3.00000,1.640756,293.571985,481.078352,481.275685,2.099813,1.578975,1.938268,2.073120,...,2.055138,1.661254,1.972319,1.987724,2.051112,2.025393,1.685038,6.073616,1.000000,3.000000
max,20.000000,3.00000,3.742152,351.416189,595.035716,595.808908,4.814811,3.977905,4.460191,4.912051,...,4.817971,3.236546,4.140010,4.326084,5.349086,4.672516,4.055203,25.000000,1.000000,3.000000

In [4]:
df.isnull().sum()

Sample_ID                               0
Batch_ID                                0
Biological_Group                        0
Peak_Current_uA                       117
Peak_Potential_mV                     124
                                     ...
Metabolite_19                         120
Metabolite_20                         130
Target_Analyte_Concentration_ng_mL      0
Detection_Label                         0
Analyte_Class                           0
Length: 81, dtype: int64

In [6]:
df[["Metabolite_19", "Metabolite_20"]] = df[["Metabolite_19", "Metabolite_20"]].fillna(df[["Metabolite_19", "Metabolite_20"]].median())

In [7]:
df.isnull().sum()

Sample_ID                               0
Batch_ID                                0
Biological_Group                        0
Peak_Current_uA                       117
Peak_Potential_mV                     124
                                     ...
Metabolite_19                           0
Metabolite_20                           0
Target_Analyte_Concentration_ng_mL      0
Detection_Label                         0
Analyte_Class                           0
Length: 81, dtype: int64

In [5]:
df.columns.duplicated().sum()

np.int64(0)

# Model Evaluation

In [9]:
candidate_features = ["Gene_14", "Protein_19", "Protein_20","Metabolite_14", "Metabolite_18", "Metabolite_20"]
X = df[candidate_features]
y = df["Target_Analyte_Concentration_ng_mL"]

In [10]:
print(X.shape)
print(y.shape)
display(X.head())
display(y.head())

(20000, 6)
(20000,)

,Gene_14,Protein_19,Protein_20,Metabolite_14,Metabolite_18,Metabolite_20
0,6.121094,1.289433,1.822502,1.066286,0.061526,1.624034
1,4.498147,2.163256,2.138160,1.386526,1.197033,1.175733
2,6.669790,2.630567,1.962040,2.215326,0.666905,1.986004
3,4.978027,2.095343,2.053430,2.699094,1.916961,1.684955
4,3.350793,1.433922,1.406283,0.020578,0.499590,1.009440

0    2.580320
1    2.128033
2    6.015071
3    5.832540
4    0.745621
Name: Target_Analyte_Concentration_ng_mL, dtype: float64

# RandomForest Regressor Model Performance

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2,  random_state=42)
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(  n_estimators=100, random_state=42)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np
r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
print("R²:", r2)
print("MAE:", mae)
print("RMSE:", rmse)

R²: 0.5221542716223501
MAE: 1.993014127616685
RMSE: 2.9315284946592937

# Candidate Molecular Feature Importance

In [14]:
# According to the results six genes/proteins/metabolites contributed most to the Random Forest predictions:
importance = pd.DataFrame({"Feature": X.columns,  "Importance": model.feature_importances_})
importance = importance.sort_values( "Importance", ascending=False)
display(importance)

         Feature  Importance
5  Metabolite_20    0.253582
2     Protein_20    0.222555
1     Protein_19    0.138025
3  Metabolite_14    0.130359
4  Metabolite_18    0.128198
0        Gene_14    0.127280

# Results

In [ ]:
# The model explained approximately 52.2% of the variation in the target analyte concentration in the test set.
# Metabolite_20 demonstrated the strongest association with the target analyte (Spearman ρ = 0.526).
# It showed the highest feature importance in the Random Forest regression model (importance = 0.254).

# Report

In [ ]:
# Report: Among the six selected features, Protein_20 and Metabolite_20, showed relatively high predictive importance in the Random Forest model 
# (importance = 0.223), indicating that they may associated with the observed target analyte concentration.
# However, it doesnot surely say that both selected Protein_20 and Metabolite_20, are target analytes or a causal biomarkers.
# Further validation using independent datasets and experimental approaches would be required.